import React,{useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {Activity,ArrowUpRight,Bell,BrainCircuit,CheckCircle2,ChevronRight,Clock3,LayoutDashboard,Menu,Plus,Settings,ShieldCheck,Sparkles,Workflow,Zap,Send,LoaderCircle} from "lucide-react";
import "./styles.css";
import {getDashboard,createWorkflow} from "./api";

const initialWorkflows=[
 {name:"Lead qualification",trigger:"New form submission",runs:128,status:"Active",success:"96%"},
 {name:"Support reply assistant",trigger:"New support ticket",runs:84,status:"Active",success:"93%"},
 {name:"Weekly sales summary",trigger:"Every Monday · 09:00",runs:24,status:"Paused",success:"100%"},
 {name:"Invoice follow-up",trigger:"Invoice 7 days overdue",runs:61,status:"Active",success:"98%"}
];
const activity=[["Lead qualification","Completed successfully","2 min ago"],["Support reply assistant","AI draft generated","18 min ago"],["Invoice follow-up","Completed successfully","42 min ago"],["Weekly sales summary","Workflow paused","1 hr ago"]];
function App(){
 const [mobile,setMobile]=useState(false); const [aiInput,setAiInput]=useState(""); const [aiResult,setAiResult]=useState(""); const [aiLoading,setAiLoading]=useState(false); const [tab,setTab]=useState("Overview"); const [workflows,setWorkflows]=useState(initialWorkflows); const [stats,setStats]=useState(null); const [apiState,setApiState]=useState("demo");
 React.useEffect(()=>{getDashboard().then(d=>{setStats(d);setWorkflows(d.workflows?.length?d.workflows:initialWorkflows);setApiState("live")}).catch(()=>setApiState("demo"))},[]);
 const visible=useMemo(()=>tab==="Overview"?workflows:tab==="Automations"?workflows.filter(x=>true):workflows,[tab,workflows]);
 async async function suggest(){if(!aiInput.trim())return;setAiLoading(true);setAiResult("");try{const r=await fetch((import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8000/api")+"/ai/suggest/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({description:aiInput})});const d=await r.json();setAiResult(d.proposal||d.message||d.detail||"No suggestion returned.");}catch{setAiResult("Connect the Django API and configure OPENAI_API_KEY to use AI suggestions.")}finally{setAiLoading(false)}}
 async function add(){const draft={name:"New AI workflow",trigger:"Configure trigger",status:"draft",runs:0,success_rate:0};try{const created=await createWorkflow(draft);setWorkflows(w=>[created,...w]);setApiState("live")}catch{setWorkflows(w=>[{name:"New AI workflow",trigger:"Configure trigger",runs:0,status:"Draft",success:"—"},...w])}setTab("Automations")}
 return <div className="app">
  <aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><div className="brandMark"><Sparkles size={18}/></div><span>AutoPilot AI</span></div><nav>{["Overview","Automations","Activity","Integrations"].map((x,i)=><button className={tab===x?"nav active":"nav"} onClick={()=>{setTab(x);setMobile(false)}} key={x}>{[LayoutDashboard,Workflow,Activity,Zap][i]({size:18})}{x}</button>)}</nav><div className="sideBottom"><button className="nav"><Settings size={18}/>Settings</button><div className="profile"><div className="avatar">SP</div><div><b>SSVPrasad</b><small>Workspace owner</small></div></div></div></aside>
  <main><header><button className="menu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><p className="eyebrow">WORKSPACE / BUSINESS OPS</p><h1>{tab==="Overview"?"Good morning, SSVPrasad.":"Automation workspace"}</h1></div><div className="headerActions"><button className="iconBtn"><Bell size={18}/><i/></button><button className="primary" onClick={add}><Plus size={18}/>New automation</button></div></header>
  <section className="content">{tab==="Overview"?<><div className="hero"><div><span className="pill"><Sparkles size={14}/> AI operations · {apiState==="live"?"Live API":"Demo mode"}</span><h2>Turn repetitive work into <span>automated workflows.</span></h2><p>Design, run and monitor AI-assisted business processes from one focused workspace.</p><button className="heroBtn" onClick={add}>Create workflow <ArrowUpRight size={17}/></button></div><div className="orb"><BrainCircuit size={82}/><div className="orbit o1"/><div className="orbit o2"/></div></div>
  <div className="aiBuilder"><div><span className="pill"><BrainCircuit size={14}/> AI workflow builder</span><h3>Describe the repetitive task you want to automate.</h3><p>Example: “When a new lead arrives, qualify it, draft a reply and log the result.”</p></div><div className="aiForm"><textarea value={aiInput} onChange={e=>setAiInput(e.target.value)} placeholder="Describe a business process..."/><button className="primary" onClick={suggest} disabled={aiLoading}>{aiLoading?<LoaderCircle className="spin" size={17}/>:<Send size={17}/>} {aiLoading?"Generating":"Generate workflow"}</button></div>{aiResult&&<div className="aiResult"><b>AI proposal</b><pre>{aiResult}</pre></div>}</div><div className="stats">{[["Automations",stats?.automations??12,`${stats?.active??4} active`,Workflow],["Successful runs",stats?.successful_runs??297,`${stats?.average_success_rate??98.2}% success`,CheckCircle2],["Time saved","38.4h","this month",Clock3],["AI actions","1,284","+18% vs last month",BrainCircuit]].map(([a,b,c,I])=><div className="stat" key={a}><div className="statTop"><span>{a}</span><I size={18}/></div><strong>{b}</strong><small>{c}</small></div>)}</div>
  <div className="grid"><div className="panel"><div className="panelHead"><div><h3>Active workflows</h3><p>Monitor your most important automations.</p></div><button className="textBtn" onClick={()=>setTab("Automations")}>View all <ChevronRight size={16}/></button></div>{workflows.slice(0,3).map(w=><WorkflowRow key={w.name} w={w}/>)}</div><div className="panel"><div className="panelHead"><div><h3>Recent activity</h3><p>Latest workflow events.</p></div></div>{activity.map(([a,b,c])=><div className="event" key={a}><div className="eventIcon"><Activity size={15}/></div><div><b>{a}</b><span>{b}</span></div><time>{c}</time></div>)}</div></div></>:<div className="panel full"><div className="panelHead"><div><h3>{tab}</h3><p>{tab==="Automations"?"Create and manage AI-powered workflows.":"Workspace events and connected business systems."}</p></div><button className="primary" onClick={add}><Plus size={17}/>New automation</button></div>{tab==="Automations"&&visible.map(w=><WorkflowRow key={w.name} w={w} />)}{tab!=="Automations"&&<Empty tab={tab}/>}</div>}</section></main></div>}
function WorkflowRow({w}){return <div className="workflow"><div className="workflowIcon"><Workflow size={18}/></div><div className="wfMain"><b>{w.name}</b><span>{w.trigger}</span></div><div className="wfMetric"><b>{w.runs}</b><span>runs</span></div><div className="wfMetric"><b>{w.success}</b><span>success</span></div><span className={"status "+w.status.toLowerCase()}>{w.status}</span><ChevronRight size={17} className="chev"/></div>}
function Empty({tab}){return <div className="empty"><div className="emptyIcon"><ShieldCheck size={28}/></div><h3>{tab} ready</h3><p>Connect this workspace to your backend and integrations to populate live data.</p></div>}
createRoot(document.getElementById("root")).render(<App/>);