import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {Activity,ArrowUpRight,Bell,BrainCircuit,CheckCircle2,ChevronRight,Clock3,Database,FlaskConical,LayoutDashboard,LoaderCircle,Mail,Menu,Play,Plus,RefreshCw,Send,Settings,ShieldCheck,Sparkles,Workflow,Webhook,Zap} from "lucide-react";
import "./styles.css";
import {getDashboard,createWorkflow,runWorkflow,runLeadDemo,runSupportDemo,runExtractDemo,runMessageDemo,createStep,submitEnquiry} from "./api";

const navItems=[["Overview",LayoutDashboard],["Automations",Workflow],["Live Demo",FlaskConical],["Activity",Activity],["Integrations",Zap]];
const actionTypes={ai:["AI Process",BrainCircuit],webhook:["Webhook",Webhook],email:["Email",Mail],transform:["Transform",RefreshCw],log:["Log",Database]};
const demoCards=[
 {id:"lead",title:"AI Lead Qualification",desc:"Classify a fictional enquiry and generate a suggested response.",icon:BrainCircuit},
 {id:"support",title:"AI Customer Support",desc:"Identify intent and answer using a safe demo knowledge base.",icon:ShieldCheck},
 {id:"extract",title:"AI Data Extraction",desc:"Turn unstructured business text into structured fields.",icon:Database},
 {id:"message",title:"AI Message Generator",desc:"Draft a professional message with a preview-only workflow.",icon:Mail}
];

function App(){
 const [mobile,setMobile]=useState(false),[tab,setTab]=useState("Overview"),[data,setData]=useState({automations:0,active:0,total_runs:0,failed_runs:0,average_success_rate:0,workflows:[],activity:[],executions:[]}),[apiState,setApiState]=useState("connecting");
 const [aiInput,setAiInput]=useState("Qualify new website leads and prepare a personalized response."),[aiResult,setAiResult]=useState(""),[aiProposal,setAiProposal]=useState(null),[aiLoading,setAiLoading]=useState(false),[creating,setCreating]=useState(false);
 const refresh=async()=>{try{setData(await getDashboard());setApiState("live")}catch{setApiState("offline")}};
 useEffect(()=>{refresh()},[]);
 async function suggest(){if(!aiInput.trim())return;setAiLoading(true);setAiResult("");setAiProposal(null);try{const r=await fetch((import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8000/api")+"/ai/suggest/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({description:aiInput})});const d=await r.json();setAiResult(d.proposal||d.message||d.detail||"No proposal returned.");setAiProposal(d.workflow||null)}catch{setAiResult("AI service is unavailable. The backend can still run sandbox demos without an API key.")}finally{setAiLoading(false)}}
 async function saveWorkflow(){setCreating(true);try{const proposal=aiProposal||{workflow_name:"AI-generated workflow",trigger:aiInput,steps:[{name:"Understand request",action_type:"ai"},{name:"Prepare business action",action_type:"transform"},{name:"Record result",action_type:"log"}]};const w=await createWorkflow({name:proposal.workflow_name,trigger:proposal.trigger,status:"active"});for(let i=0;i<proposal.steps.length;i++)await createStep({workflow:w.id,name:proposal.steps[i].name,action_type:proposal.steps[i].action_type,position:i+1,config:{}});await refresh();setTab("Automations")}catch{}finally{setCreating(false)}}
 async function run(id){try{await runWorkflow(id);await refresh()}catch{}}
 return <div className="app">
  <aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><div className="brandMark"><Sparkles size={18}/></div><span>AutoPilot AI</span></div><nav>{navItems.map(([name,Icon])=><button key={name} className={tab===name?"nav active":"nav"} onClick={()=>{setTab(name);setMobile(false)}}><Icon size={18}/>{name}</button>)}</nav><div className="sideBottom"><button className="nav"><Settings size={18}/>Settings</button><div className="profile"><div className="avatar">SP</div><div><b>SSVPrasad</b><small>Portfolio workspace</small></div></div></div></aside>
  <main><header><div className="headerLeft"><button className="menu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><p className="eyebrow">AI AUTOMATION PLATFORM</p><h1>{tab==="Overview"?"Automation command center":tab}</h1></div></div><div className="headerActions"><span className={"connection "+apiState}><i/>{apiState==="live"?"Live API":apiState==="connecting"?"Connecting":"Backend offline"}</span><button className="iconBtn"><Bell size={18}/></button><button className="primary" onClick={()=>setTab("Live Demo")}><Play size={16}/>Try a demo</button></div></header>
   <section className="content">
    {tab==="Overview"&&<Overview data={data} onRun={run} onTab={setTab} aiInput={aiInput} setAiInput={setAiInput} aiResult={aiResult} aiLoading={aiLoading} suggest={suggest} saveWorkflow={saveWorkflow} creating={creating} apiState={apiState} aiProposal={aiProposal}/>}
    {tab==="Automations"&&<Automations data={data} onRun={run} onRefresh={refresh}/>}
    {tab==="Live Demo"&&<LiveAutomationLab onComplete={refresh}/>}
    {tab==="Activity"&&<ActivityPanel data={data}/>}
    {tab==="Integrations"&&<Integrations/>}
   </section></main></div>
}

function Overview({data,onRun,onTab,aiInput,setAiInput,aiResult,aiLoading,suggest,saveWorkflow,creating,apiState,aiProposal}){
 const stats=[["Automations",data.automations,data.active+" active",Workflow],["Total runs",data.total_runs,data.average_success_rate+"% success",CheckCircle2],["Execution history",data.executions?.length||0,(data.failed_runs||0)+" failed",Clock3],["AI workflows",data.workflows?.filter(w=>w.steps?.some(s=>s.action_type==="ai")).length||0,"with AI steps",BrainCircuit]];
 return <><div className="hero"><div><span className="pill"><Sparkles size={14}/> AI operations · {apiState==="live"?"Live API":"Sandbox ready"}</span><h2>Turn repetitive work into <span>automated workflows.</span></h2><p>Design, execute and observe AI-assisted business processes from one focused workspace.</p><button className="heroBtn" onClick={()=>onTab("Live Demo")}>Open Automation Lab <Play size={16}/></button></div><div className="orb"><BrainCircuit size={82}/><div className="orbit o1"/><div className="orbit o2"/></div></div>
 <div className="aiBuilder"><div><span className="pill"><BrainCircuit size={14}/> AI workflow builder</span><h3>Describe the business process.</h3><p>AI proposes a workflow, then you can save it as a real workflow with ordered action steps.</p></div><div className="aiForm"><textarea value={aiInput} onChange={e=>setAiInput(e.target.value)} placeholder="Example: qualify new website leads and prepare a response..."/><button className="primary" onClick={suggest} disabled={aiLoading}>{aiLoading?<><LoaderCircle className="spin" size={17}/>Generating</>:<><Send size={17}/>Generate</>}</button></div>{aiResult&&<div className="aiResult"><b>Workflow proposal</b><pre>{aiResult}</pre>{aiProposal&&<div className="proposalSteps"><b>Parsed workflow: {aiProposal.workflow_name}</b><span>Trigger · {aiProposal.trigger}</span><div>{aiProposal.steps.map((s,i)=><em key={i}>{i+1}. {s.name} · {s.action_type}</em>)}</div></div>}<button className="primary" onClick={saveWorkflow} disabled={creating}>{creating?<><LoaderCircle className="spin" size={16}/>Saving</>:<><Plus size={16}/>Create workflow</>}</button></div>}</div>
 <div className="stats">{stats.map(([a,b,c,I])=><div className="stat" key={a}><div className="statTop"><span>{a}</span><I size={18}/></div><strong>{b}</strong><small>{c}</small></div>)}</div>
 <div className="grid"><div className="panel"><PanelHead title="Active workflows" sub="Run and inspect configured workflows." action="View all" onClick={()=>onTab("Automations")}/>{data.workflows.filter(w=>w.status==="active").slice(0,4).map(w=><WorkflowRow key={w.id} w={w} onRun={onRun}/>)}</div><div className="panel"><PanelHead title="Recent executions" sub="Latest workflow activity." action="Activity" onClick={()=>onTab("Activity")}/>{(data.executions||[]).slice(0,5).map(e=><ExecutionRow key={e.id} e={e}/>)}</div></div></>
}

function Automations({data,onRun,onRefresh}){
 const [selected,setSelected]=useState(null),[busy,setBusy]=useState(null);
 const execute=async id=>{setBusy(id);await onRun(id);setBusy(null)};
 return <div className="panel full"><PanelHead title="Workflow builder" sub="Configure triggers, action steps and execution behavior." action="Refresh" onClick={onRefresh}/>{data.workflows.length===0?<Empty title="No workflows yet" text="Use the AI builder to create your first workflow."/>:<div className="automationList">{data.workflows.map(w=><div key={w.id} className="automationCard"><div className="automationTop"><div className="workflowIcon"><Workflow size={18}/></div><div className="wfMain"><b>{w.name}</b><span>Trigger · {w.trigger}</span></div><span className={"status "+w.status}>{w.status}</span><button className="ghost" onClick={()=>setSelected(selected===w.id?null:w.id)}>{selected===w.id?"Hide details":"View details"}</button><button className="runBtn" disabled={busy===w.id||w.status!=="active"} onClick={()=>execute(w.id)}>{busy===w.id?"Running…":<><Play size={13}/>Run now</>}</button></div>{selected===w.id&&<WorkflowDetail w={w}/>}</div>)}</div>}</div>
}
function WorkflowDetail({w}){return <div className="workflowDetail"><div className="detailGrid"><div><span>Trigger</span><b>{w.trigger}</b></div><div><span>Status</span><b>{w.status}</b></div><div><span>Runs</span><b>{w.runs}</b></div><div><span>Success rate</span><b>{w.success}</b></div></div><StepList steps={w.steps||[]}/></div>
}

function StepList({steps}){return <div className="steps">{steps.length?steps.map((s,i)=>{const A=actionTypes[s.action_type]?.[1]||Zap;return <div className="step" key={s.id||i}><span className="stepNo">{i+1}</span><A size={15}/><div><b>{s.name}</b><span>{actionTypes[s.action_type]?.[0]||s.action_type}</span></div></div>}):<div className="stepEmpty">No action steps configured.</div>}</div>}

function LiveAutomationLab({onComplete}){
 const [selected,setSelected]=useState("lead"),[result,setResult]=useState(null),[loading,setLoading]=useState(false);
 const [lead,setLead]=useState("I need a website for my restaurant with online ordering before Diwali.");
 const [question,setQuestion]=useState("How does the lead qualification demo work?");
 const [extract,setExtract]=useState("Acme Foods needs a website and online ordering. They want it ready before Diwali and asked for a quote.");
 const [purpose,setPurpose]=useState("follow up on a project enquiry"),[recipient,setRecipient]=useState("Potential client"),[tone,setTone]=useState("Professional"),[context,setContext]=useState("We discussed building an AI-enabled website and I want to confirm the next steps.");
 const run=async()=>{
  setLoading(true);setResult(null);
  try{
   const r=selected==="lead"?await runLeadDemo(lead):selected==="support"?await runSupportDemo(question):selected==="extract"?await runExtractDemo(extract):await runMessageDemo({purpose,recipient,tone,context});
   setResult(r);await onComplete();
  }catch(e){setResult({demo:{mode:"offline",result:"The demo API is unavailable. Start the Django backend or configure the deployed API."}})}
  finally{setLoading(false)}
 };
 const input=selected==="lead"?<Field label="Customer enquiry"><textarea value={lead} onChange={e=>setLead(e.target.value)}/></Field>:selected==="support"?<Field label="Customer question"><textarea value={question} onChange={e=>setQuestion(e.target.value)}/></Field>:selected==="extract"?<Field label="Business text / document content"><textarea value={extract} onChange={e=>setExtract(e.target.value)}/></Field>:<div className="messageFields"><Field label="Purpose"><input value={purpose} onChange={e=>setPurpose(e.target.value)}/></Field><Field label="Recipient type"><input value={recipient} onChange={e=>setRecipient(e.target.value)}/></Field><Field label="Tone"><select value={tone} onChange={e=>setTone(e.target.value)}><option>Professional</option><option>Friendly</option><option>Concise</option><option>Formal</option></select></Field><Field label="Context"><textarea value={context} onChange={e=>setContext(e.target.value)}/></Field></div>;
 return <div className="demoShell"><div className="demoIntro"><span className="pill"><FlaskConical size={14}/> Sandboxed live automation lab</span><h2>Run the workflows yourself.</h2><p>These are safe portfolio demonstrations. They process your input but do not send emails, modify CRMs, execute arbitrary code, or create external side effects.</p></div><div className="demoCards">{demoCards.map(({id,title,desc,icon:Icon})=><button key={id} className={"demoCard "+(selected===id?"selected":"")} onClick={()=>{setSelected(id);setResult(null)}}><Icon size={20}/><b>{title}</b><span>{desc}</span></button>)}</div><div className="demoGrid"><div className="panel demoInput"><div className="demoPanelTitle"><div><b>Configure workflow</b><span>Input → process → result</span></div><span className="safeBadge"><ShieldCheck size={13}/> Safe sandbox</span></div>{input}<button className="primary" onClick={run} disabled={loading}>{loading?<><LoaderCircle className="spin" size={17}/>Running workflow</>:<><Play size={17}/>Run live automation</>}</button><div className="demoFlow"><span>1 · Validate input</span><span>2 · AI / rule processing</span><span>3 · Quality check</span><span>4 · Return structured result</span></div></div><div className="panel resultPanel"><div className="resultHead"><div><b>Execution result</b><span className="resultSub">Latest run output</span></div>{result&&<span className="status active">{result.demo?.mode==="ai"?"AI":"Sandbox"} result</span>}</div>{result?<pre>{typeof result.demo?.result==="string"?result.demo.result:JSON.stringify(result.demo?.result??result.result,null,2)}</pre>:<Empty title="Ready to run" text="Your workflow output will appear here."/>}</div></div><div className="labFooter"><span><ShieldCheck size={16}/> No external side effects</span><span><Activity size={16}/> Every run is logged</span><span><Workflow size={16}/> Built on the same workflow engine</span></div><EnquiryCTA/></div>
}

function EnquiryCTA(){
 const [open,setOpen]=useState(false),[form,setForm]=useState({name:"",email:"",business_process:"",integration:""}),[sending,setSending]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState("");
 async function submit(e){e.preventDefault();setSending(true);setError("");try{await submitEnquiry(form);setSent(true);setForm({name:"",email:"",business_process:"",integration:""})}catch{setError("We could not submit the enquiry. Please try again.")}finally{setSending(false)}}
 return <section className="enquiry"><div><span className="pill"><Sparkles size={14}/> Freelance automation</span><h3>Need something like this for your business?</h3><p>Describe the repetitive process you want to automate. This enquiry form is for project discovery; it does not send automated messages to third parties.</p></div>{!open?<button className="primary" onClick={()=>setOpen(true)}>Build my automation <ArrowUpRight size={16}/></button>:sent?<div className="enquirySuccess"><CheckCircle2 size={18}/> Enquiry recorded. Thank you.</div>:<form onSubmit={submit} className="enquiryForm"><input required placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><select value={form.integration} onChange={e=>setForm({...form,integration:e.target.value})}><option value="">Integration needed (optional)</option><option>Webhook / form</option><option>Email</option><option>CRM / API</option><option>AI provider</option><option>Not sure</option></select><textarea required placeholder="What repetitive process would you like to automate?" value={form.business_process} onChange={e=>setForm({...form,business_process:e.target.value})}/>{error&&<small className="formError">{error}</small>}<button className="primary" disabled={sending}>{sending?<><LoaderCircle className="spin" size={16}/>Submitting</>: "Submit enquiry"}</button></form>}</section>
}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function ActivityPanel({data}){return <div className="panel full"><PanelHead title="Execution activity" sub="Step-level and workflow-level execution history."/><div className="activityList">{data.activity?.length?data.activity.map(x=><div className="log" key={x.id}><div className="eventIcon"><CheckCircle2 size={15}/></div><div><b>{x.workflow}</b><span>{x.message}</span></div><time>{new Date(x.created_at).toLocaleString()}</time></div>):<Empty title="No executions yet" text="Run an active workflow or try the Live Automation Lab."/>}</div></div>}
function Integrations(){return <div className="panel full"><PanelHead title="Integration layer" sub="Connection points prepared for real business systems."/><div className="integrationGrid">{[["Webhooks","Receive events from websites and forms",Webhook],["Email","Send approved workflow outputs",Mail],["AI providers","Process and transform business data",BrainCircuit],["CRM / APIs","Push structured results into external systems",Database]].map(([a,b,I])=><div className="integrationCard" key={a}><div className="integrationIcon"><I size={20}/></div><b>{a}</b><p>{b}</p><span>Adapter ready · connection required</span></div>)}</div><div className="notice"><ShieldCheck size={18}/><span>External side effects are disabled in the public demo until a real integration is configured.</span></div></div>}
function WorkflowRow({w,onRun}){const [busy,setBusy]=useState(false);return <div className="workflow"><div className="workflowIcon"><Workflow size={18}/></div><div className="wfMain"><b>{w.name}</b><span>{w.trigger}</span></div><div className="wfMetric"><b>{w.runs}</b><span>runs</span></div><div className="wfMetric"><b>{w.success}</b><span>success</span></div><span className={"status "+w.status}>{w.status}</span><button className="runBtn" disabled={busy||w.status!=="active"} onClick={async()=>{setBusy(true);await onRun(w.id);setBusy(false)}}>{busy?"Running…":"Run now"}</button></div>}
function ExecutionRow({e}){return <div className="event"><div className="eventIcon"><CheckCircle2 size={15}/></div><div><b>{e.workflow}</b><span>{e.status} execution</span></div><time>{new Date(e.started_at).toLocaleString()}</time></div>}
function PanelHead({title,sub,action,onClick}){return <div className="panelHead"><div><h3>{title}</h3><p>{sub}</p></div>{action&&<button className="textBtn" onClick={onClick}>{action}<ChevronRight size={16}/></button>}</div>}
function Empty({title,text}){return <div className="empty"><div className="emptyIcon"><ShieldCheck size={28}/></div><h3>{title}</h3><p>{text}</p></div>}
createRoot(document.getElementById("root")).render(<App/>);