import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {Activity,ArrowUpRight,Bell,BrainCircuit,CheckCircle2,ChevronRight,Clock3,LayoutDashboard,Menu,Plus,Settings,ShieldCheck,Sparkles,Workflow,Zap,Send,LoaderCircle,Play,FlaskConical,Webhook,Mail,Database,RefreshCw} from "lucide-react";
import "./styles.css";
import {getDashboard,createWorkflow,runWorkflow,runLeadDemo,createStep} from "./api";

const navItems=[["Overview",LayoutDashboard],["Automations",Workflow],["Live Demo",FlaskConical],["Activity",Activity],["Integrations",Zap]];
const actionTypes={ai:["AI Process",BrainCircuit],webhook:["Webhook",Webhook],email:["Email",Mail],transform:["Transform",RefreshCw],log:["Log",Database]};

function App(){
 const [mobile,setMobile]=useState(false),[tab,setTab]=useState("Overview"),[data,setData]=useState({automations:0,active:0,successful_runs:0,average_success_rate:0,workflows:[],activity:[],executions:[]}),[apiState,setApiState]=useState("connecting");
 const [aiInput,setAiInput]=useState(""),[aiResult,setAiResult]=useState(""),[aiLoading,setAiLoading]=useState(false),[creating,setCreating]=useState(false);
 const [demoInput,setDemoInput]=useState("I need a website for my restaurant with online ordering before Diwali."),[demoResult,setDemoResult]=useState(null),[demoLoading,setDemoLoading]=useState(false);
 const refresh=async()=>{try{setData(await getDashboard());setApiState("live")}catch{setApiState("offline")}};
 useEffect(()=>{refresh()},[]);
 async function suggest(){if(!aiInput.trim())return;setAiLoading(true);setAiResult("");try{const r=await fetch((import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8000/api")+"/ai/suggest/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({description:aiInput})});const d=await r.json();setAiResult(d.proposal||d.message||d.detail||"No proposal returned.")}catch{setAiResult("AI service is not configured. Add OPENAI_API_KEY to the backend.")}finally{setAiLoading(false)}}
 async function saveWorkflow(){setCreating(true);try{const w=await createWorkflow({name:"AI-generated workflow",trigger:aiInput,status:"active",runs:0,success_rate:0});const steps=[["Understand request","ai"],["Prepare business action","transform"],["Record result","log"]];for(let i=0;i<steps.length;i++)await createStep({workflow:w.id,name:steps[i][0],action_type:steps[i][1],position:i+1,config:{}});await refresh()}catch{}finally{setCreating(false)}}
 async function run(id){try{await runWorkflow(id);await refresh()}catch{}}
 async function leadDemo(){if(!demoInput.trim())return;setDemoLoading(true);setDemoResult(null);try{setDemoResult(await runLeadDemo(demoInput))}catch{setDemoResult({mode:"offline",result:"Demo API is unavailable. Start the Django backend to run this live."})}finally{setDemoLoading(false)}}
 return <div className="app">
  <aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><div className="brandMark"><Sparkles size={18}/></div><span>AutoPilot AI</span></div><nav>{navItems.map(([name,Icon])=><button key={name} className={tab===name?"nav active":"nav"} onClick={()=>{setTab(name);setMobile(false)}}><Icon size={18}/>{name}</button>)}</nav><div className="sideBottom"><button className="nav"><Settings size={18}/>Settings</button><div className="profile"><div className="avatar">SP</div><div><b>SSVPrasad</b><small>Portfolio workspace</small></div></div></div></aside>
  <main><header><div className="headerLeft"><button className="menu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><p className="eyebrow">AI AUTOMATION PLATFORM</p><h1>{tab==="Overview"?"Automation command center":tab}</h1></div></div><div className="headerActions"><span className={"connection "+apiState}><i/>{apiState==="live"?"Live API":apiState==="connecting"?"Connecting":"Backend offline"}</span><button className="iconBtn"><Bell size={18}/></button><button className="primary" onClick={()=>setTab("Automations")}><Plus size={18}/>New automation</button></div></header>
   <section className="content">{tab==="Overview"&&<Overview data={data} onRun={run} onTab={setTab}/>}
   {tab==="Automations"&&<Automations data={data} onRun={run} onRefresh={refresh}/>}
   {tab==="Live Demo"&&<LiveDemo input={demoInput} setInput={setDemoInput} result={demoResult} loading={demoLoading} onRun={leadDemo}/>}
   {tab==="Activity"&&<ActivityPanel data={data}/>}
   {tab==="Integrations"&&<Integrations/>}
   </section></main></div>
}

function Overview({data,onRun,onTab}){
 const stats=[["Automations",data.automations,data.active+" active",Workflow],["Successful runs",data.successful_runs,data.average_success_rate+"% success",CheckCircle2],["Execution history",data.executions?.length||0,"recent runs",Clock3],["AI workflows",data.workflows?.filter(w=>w.steps?.some(s=>s.action_type==="ai")).length||0,"with AI steps",BrainCircuit]];
 return <><div className="hero"><div><span className="pill"><Sparkles size={14}/> AI operations · Live API</span><h2>Turn repetitive work into <span>automated workflows.</span></h2><p>Design, execute and observe AI-assisted business processes from one focused workspace.</p><button className="heroBtn" onClick={()=>onTab("Live Demo")}>Try a live automation <Play size={16}/></button></div><div className="orb"><BrainCircuit size={82}/><div className="orbit o1"/><div className="orbit o2"/></div></div>
 <div className="stats">{stats.map(([a,b,c,I])=><div className="stat" key={a}><div className="statTop"><span>{a}</span><I size={18}/></div><strong>{b}</strong><small>{c}</small></div>)}</div>
 <div className="grid"><div className="panel"><PanelHead title="Active workflows" sub="Run and inspect configured workflows." action="View all" onClick={()=>onTab("Automations")}/>{data.workflows.filter(w=>w.status==="Active"||w.status==="active").slice(0,4).map(w=><WorkflowRow key={w.id} w={w} onRun={onRun}/>)}</div><div className="panel"><PanelHead title="Recent executions" sub="Latest workflow activity." action="Activity" onClick={()=>onTab("Activity")}/>{(data.executions||[]).slice(0,5).map(e=><ExecutionRow key={e.id} e={e}/>)}</div></div></>
}

function Automations({data,onRun,onRefresh}){
 const [selected,setSelected]=useState(null),[busy,setBusy]=useState(null);
 const execute=async id=>{setBusy(id);await onRun(id);setBusy(null)};
 return <div className="panel full"><PanelHead title="Workflow builder" sub="Configure triggers, action steps and execution behavior." action="Refresh" onClick={onRefresh}/>{data.workflows.length===0?<Empty title="No workflows yet" text="Use the AI builder to create your first workflow."/>:<div className="automationList">{data.workflows.map(w=><div key={w.id} className="automationCard"><div className="automationTop"><div className="workflowIcon"><Workflow size={18}/></div><div className="wfMain"><b>{w.name}</b><span>Trigger · {w.trigger}</span></div><span className={"status "+w.status.toLowerCase()}>{w.status}</span><button className="ghost" onClick={()=>setSelected(selected===w.id?null:w.id)}>{selected===w.id?"Hide steps":"View steps"}</button><button className="runBtn" disabled={busy===w.id||!(w.status==="Active"||w.status==="active")} onClick={()=>execute(w.id)}>{busy===w.id?"Running…":<><Play size={13}/>Run now</>}</button></div>{selected===w.id&&<StepList steps={w.steps||[]}/>}</div>)}</div>}</div>
}

function StepList({steps}){return <div className="steps">{steps.length?steps.map((s,i)=>{const A=actionTypes[s.action_type]?.[1]||Zap;return <div className="step" key={s.id||i}><span className="stepNo">{i+1}</span><A size={15}/><div><b>{s.name}</b><span>{actionTypes[s.action_type]?.[0]||s.action_type}</span></div></div>}):<div className="stepEmpty">No action steps configured.</div>}</div>}

function LiveDemo({input,setInput,result,loading,onRun}){return <div className="demoShell"><div className="demoIntro"><span className="pill"><FlaskConical size={14}/> Sandboxed live demo</span><h2>AI Lead Qualification</h2><p>Enter a fictional customer enquiry. The workflow analyzes it and returns a qualification result. It has no external side effects.</p></div><div className="demoGrid"><div className="panel demoInput"><label>Customer enquiry</label><textarea value={input} onChange={e=>setInput(e.target.value)}/><button className="primary" onClick={onRun} disabled={loading}>{loading?<><LoaderCircle className="spin" size={17}/>Running workflow</>:<><Play size={17}/>Run live demo</>}</button><div className="demoFlow"><span>1 · Receive enquiry</span><span>2 · AI qualification</span><span>3 · Generate response</span><span>4 · Return result</span></div></div><div className="panel resultPanel"><div className="resultHead"><b>Execution result</b>{result&&<span className="status active">{result.mode==="ai"?"AI":"Sandbox"} result</span>}</div>{result?<pre>{typeof result.result==="string"?result.result:JSON.stringify(result.result,null,2)}</pre>:<Empty title="Ready to run" text="Your workflow output will appear here."/>}</div></div></div>}

function ActivityPanel({data}){return <div className="panel full"><PanelHead title="Execution activity" sub="Step-level and workflow-level execution history."/><div className="activityList">{data.activity?.length?data.activity.map(x=><div className="log" key={x.id}><div className="eventIcon"><CheckCircle2 size={15}/></div><div><b>{x.workflow}</b><span>{x.message}</span></div><time>{new Date(x.created_at).toLocaleString()}</time></div>):<Empty title="No executions yet" text="Run an active workflow or try the Live Demo."/>}</div></div>}

function Integrations(){return <div className="panel full"><PanelHead title="Integration layer" sub="Connection points prepared for real business systems."/><div className="integrationGrid">{[["Webhooks","Receive events from websites and forms",Webhook],["Email","Send approved workflow outputs",Mail],["AI providers","Process and transform business data",BrainCircuit],["CRM / APIs","Push structured results into external systems",Database]].map(([a,b,I])=><div className="integrationCard" key={a}><div className="integrationIcon"><I size={20}/></div><b>{a}</b><p>{b}</p><span>Adapter ready · connection required</span></div>)}</div><div className="notice"><ShieldCheck size={18}/><span>External side effects are disabled in the public demo until a real integration is configured.</span></div></div>}

function WorkflowRow({w,onRun}){const [busy,setBusy]=useState(false);return <div className="workflow"><div className="workflowIcon"><Workflow size={18}/></div><div className="wfMain"><b>{w.name}</b><span>{w.trigger}</span></div><div className="wfMetric"><b>{w.runs}</b><span>runs</span></div><div className="wfMetric"><b>{w.success}</b><span>success</span></div><span className={"status "+w.status.toLowerCase()}>{w.status}</span><button className="runBtn" disabled={busy||w.status.toLowerCase()!=="active"} onClick={async()=>{setBusy(true);await onRun(w.id);setBusy(false)}}>{busy?"Running…":"Run now"}</button></div>}
function ExecutionRow({e}){return <div className="event"><div className="eventIcon"><CheckCircle2 size={15}/></div><div><b>{e.workflow}</b><span>{e.status} execution</span></div><time>{new Date(e.started_at).toLocaleString()}</time></div>}
function PanelHead({title,sub,action,onClick}){return <div className="panelHead"><div><h3>{title}</h3><p>{sub}</p></div>{action&&<button className="textBtn" onClick={onClick}>{action}<ChevronRight size={16}/></button>}</div>}
function Empty({title,text}){return <div className="empty"><div className="emptyIcon"><ShieldCheck size={28}/></div><h3>{title}</h3><p>{text}</p></div>}
createRoot(document.getElementById("root")).render(<App/>);
